
import React, { useState, useEffect, useRef } from 'react';
import { 
  Users, MapPin, Building, GraduationCap, Briefcase, Award, TrendingUp, 
  DollarSign, PieChart as PieIcon, CheckCircle, AlertTriangle, FileText, ArrowUpRight, 
  Zap, Settings, Globe, Printer, ChevronUp, ChevronDown, FileBarChart, Presentation
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
// @ts-ignore
import pptxgen from 'pptxgenjs';
import SlideLayout from './components/SlideLayout';
import Sidebar from './components/Sidebar';
import { SimpleBarChart, CustomPieChart, CustomLineChart } from './components/ChartComponents';
import { SLIDES, COLORS } from './constants';

const App: React.FC = () => {
  const [activeId, setActiveId] = useState('title');
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleScroll = () => {
      if (!scrollRef.current) return;
      const scrollPos = scrollRef.current.scrollTop;
      const height = window.innerHeight;
      const currentIdx = Math.round(scrollPos / height);
      if (SLIDES[currentIdx]) {
        setActiveId(SLIDES[currentIdx].id);
      }
    };

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'ArrowDown' || e.key === 'ArrowRight') {
        navigateSlide('next');
      } else if (e.key === 'ArrowUp' || e.key === 'ArrowLeft') {
        navigateSlide('prev');
      }
    };

    const currentScrollRef = scrollRef.current;
    currentScrollRef?.addEventListener('scroll', handleScroll);
    window.addEventListener('keydown', handleKeyDown);
    
    return () => {
      currentScrollRef?.removeEventListener('scroll', handleScroll);
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, []);

  const navigateSlide = (direction: 'next' | 'prev') => {
    const currentIdx = SLIDES.findIndex(s => s.id === activeId);
    let nextIdx = direction === 'next' ? currentIdx + 1 : currentIdx - 1;
    
    if (nextIdx >= 0 && nextIdx < SLIDES.length) {
      const targetId = SLIDES[nextIdx].id;
      const element = document.getElementById(targetId);
      element?.scrollIntoView({ behavior: 'smooth' });
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleExportPPT = () => {
    let pptx = new pptxgen();
    
    pptx.defineLayout({ name: 'A4', width: 10, height: 7.5 });
    pptx.layout = 'A4';

    // Slide 1: Title
    let slide1 = pptx.addSlide();
    slide1.background = { color: '0B5D3B' };
    slide1.addText('Govt. Technical Training Institute (GTTI)\nRahim Yar Khan', {
      x: 0, y: 1.5, w: '100%', align: 'center', fontSize: 24, color: 'C9A227', bold: true
    });
    slide1.addText('Institutional Progress & Financial Status Report', {
      x: 0, y: 3.5, w: '100%', align: 'center', fontSize: 44, color: 'FFFFFF', bold: true
    });
    slide1.addText('Jan 2026', {
      x: 0, y: 5.5, w: '100%', align: 'center', fontSize: 18, color: 'C9A227'
    });

    // Slides 2-15: Basic mapping (Title + Body text)
    SLIDES.slice(1).forEach((item) => {
      let slide = pptx.addSlide();
      slide.addText(item.title, {
        x: 0.5, y: 0.5, w: 9, h: 1, fontSize: 32, color: '0B5D3B', bold: true, border: { type: 'solid', color: 'C9A227', pt: 2 }
      });
      slide.addText('Institutional Progress and Financial Summary Data', {
        x: 0.5, y: 2, w: 9, h: 4, fontSize: 18, color: '333333', bullet: true
      });
      slide.addText('Report generated by GTTI Management System', {
        x: 0.5, y: 6.5, w: 9, fontSize: 10, color: '666666', align: 'right'
      });
    });

    pptx.writeFile({ fileName: 'GTTI_Institutional_Report_2026.pptx' });
  };

  return (
    <div className="relative h-screen bg-slate-50 overflow-hidden flex">
      <Sidebar 
        isOpen={isSidebarOpen} 
        onToggle={() => setIsSidebarOpen(!isSidebarOpen)} 
        activeId={activeId} 
      />

      <div className="flex-grow md:ml-72 relative">
        {/* Navigation Controls Header */}
        <div className="absolute top-6 right-8 z-50 flex items-center gap-3 no-print">
          <button 
            onClick={handleExportPPT}
            className="flex items-center gap-2 px-4 py-2 bg-[#C9A227] text-white rounded-full shadow-md hover:bg-[#b08d20] transition-all font-bold text-xs md:text-sm"
          >
            <Presentation size={16} /> Export PPT
          </button>
          <button 
            onClick={handlePrint}
            className="flex items-center gap-2 px-4 py-2 bg-white text-slate-700 rounded-full border border-slate-200 shadow-md hover:bg-slate-50 transition-all font-medium text-xs md:text-sm"
          >
            <Printer size={16} /> PDF
          </button>
        </div>

        {/* Floating Next/Prev Buttons */}
        <div className="fixed bottom-10 right-10 z-50 flex flex-col gap-3 no-print">
          <button 
            onClick={() => navigateSlide('prev')}
            disabled={activeId === SLIDES[0].id}
            className={`p-3 rounded-full shadow-2xl transition-all border border-white/20 backdrop-blur-md ${activeId === SLIDES[0].id ? 'bg-slate-200 text-slate-400 cursor-not-allowed' : 'bg-[#0B5D3B] text-[#C9A227] hover:scale-110 active:scale-95'}`}
            title="Previous Slide"
          >
            <ChevronUp size={24} />
          </button>
          <button 
            onClick={() => navigateSlide('next')}
            disabled={activeId === SLIDES[SLIDES.length - 1].id}
            className={`p-3 rounded-full shadow-2xl transition-all border border-white/20 backdrop-blur-md ${activeId === SLIDES[SLIDES.length - 1].id ? 'bg-slate-200 text-slate-400 cursor-not-allowed' : 'bg-[#0B5D3B] text-[#C9A227] hover:scale-110 active:scale-95'}`}
            title="Next Slide"
          >
            <ChevronDown size={24} />
          </button>
        </div>

        <div ref={scrollRef} className="snap-container scroll-smooth">
          
          {/* SLIDE 1: Title */}
          <SlideLayout id="title" bgImage="https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=1600&auto=format&fit=crop">
            <div className="flex flex-col items-center justify-center text-center h-full text-white">
              <motion.div 
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8 }}
                className="mb-6"
              >
                <h3 className="text-xl md:text-3xl font-bold text-[#C9A227] tracking-[0.2em] uppercase drop-shadow-lg">
                  Govt. Technical Training Institute (GTTI)
                </h3>
                <h4 className="text-lg md:text-2xl font-semibold opacity-90 mt-2 tracking-widest uppercase">
                  Rahim Yar Khan
                </h4>
              </motion.div>

              <motion.div 
                initial={{ opacity: 0, scale: 0.5 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.8, delay: 0.2 }}
                className="w-24 h-24 md:w-32 md:h-32 bg-white rounded-full flex items-center justify-center p-4 shadow-2xl mb-10 border-4 border-[#C9A227]"
              >
                <img src="https://picsum.photos/id/42/100/100" alt="GTTI Logo" className="w-full h-full object-contain opacity-80" />
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.4 }}
              >
                <h1 className="text-5xl md:text-7xl font-black mb-6 tracking-tight max-w-4xl drop-shadow-2xl leading-tight">
                  Institutional Progress & <br/>
                  <span className="text-[#C9A227]">Financial Status Report</span>
                </h1>
                
                <div className="flex flex-col items-center gap-6 mt-10">
                  <span className="px-8 py-3 bg-[#C9A227] text-[#0B5D3B] rounded-full font-black text-sm tracking-widest uppercase shadow-xl hover:scale-105 transition-transform">
                    Reporting Period: Jan 2026
                  </span>
                  <div className="flex items-center gap-3 text-slate-200 bg-black/30 px-6 py-2 rounded-full backdrop-blur-sm">
                    <Globe size={18} className="text-[#C9A227]" />
                    <span className="text-sm font-bold uppercase tracking-wider">Affiliated with TEVTA Punjab</span>
                  </div>
                </div>

                {/* Inline Nav for Front Page */}
                <div className="mt-12 flex items-center gap-6 no-print">
                  <button onClick={() => navigateSlide('prev')} className="p-4 rounded-full border border-white/20 bg-white/10 hover:bg-white/20 transition-all">
                    <ChevronUp className="rotate-[-90deg]" size={20} />
                  </button>
                  <p className="text-sm font-bold opacity-60 uppercase tracking-widest">Start Presentation</p>
                  <button onClick={() => navigateSlide('next')} className="p-4 rounded-full border border-[#C9A227]/50 bg-[#C9A227]/20 hover:bg-[#C9A227]/40 transition-all text-[#C9A227]">
                    <ChevronDown className="rotate-[-90deg]" size={20} />
                  </button>
                </div>
              </motion.div>
            </div>
          </SlideLayout>

          {/* SLIDE 2: Institute Overview */}
          <SlideLayout id="overview" title="Institute Overview">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
              <div className="space-y-8">
                <div className="bg-white p-8 rounded-3xl shadow-xl border border-slate-100">
                  <h3 className="text-2xl font-bold text-[#0B5D3B] mb-4 flex items-center gap-3">
                    <MapPin className="text-[#C9A227]" /> Our Presence
                  </h3>
                  <p className="text-slate-600 leading-relaxed mb-6">
                    Strategically located in Rahim Yar Khan, serving as the hub for technical excellence in Southern Punjab. 
                    GTTI is committed to transforming youth into skilled professionals through rigorous training and industrial exposure.
                  </p>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="p-4 bg-slate-50 rounded-2xl">
                      <p className="text-xs text-slate-400 font-bold uppercase mb-1">Affiliation</p>
                      <p className="font-bold text-[#0B5D3B]">TEVTA Punjab</p>
                    </div>
                    <div className="p-4 bg-slate-50 rounded-2xl">
                      <p className="text-xs text-slate-400 font-bold uppercase mb-1">Region</p>
                      <p className="font-bold text-[#0B5D3B]">Bahawalpur</p>
                    </div>
                  </div>
                </div>
                <div className="bg-gradient-to-br from-[#0B5D3B] to-[#04331e] p-8 rounded-3xl text-white shadow-xl">
                  <h3 className="text-2xl font-bold mb-4">Mission Statement</h3>
                  <p className="italic opacity-90 text-lg">
                    "To provide high-quality technical education and vocational training that meets the dynamic demands of the industry and empowers students for economic self-sufficiency."
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {[
                  { icon: <GraduationCap size={32} />, label: "Quality Education", color: "bg-blue-50 text-blue-600" },
                  { icon: <Zap size={32} />, label: "Skill Mastery", color: "bg-amber-50 text-amber-600" },
                  { icon: <Briefcase size={32} />, label: "Industry Driven", color: "bg-emerald-50 text-emerald-600" },
                  { icon: <Award size={32} />, label: "Global Standards", color: "bg-purple-50 text-purple-600" },
                ].map((item, i) => (
                  <motion.div 
                    key={i}
                    whileHover={{ y: -10 }}
                    className="p-8 bg-white rounded-3xl shadow-lg border border-slate-100 flex flex-col items-center text-center gap-4"
                  >
                    <div className={`p-4 rounded-2xl ${item.color}`}>
                      {item.icon}
                    </div>
                    <span className="font-bold text-slate-800">{item.label}</span>
                  </motion.div>
                ))}
              </div>
            </div>
          </SlideLayout>

          {/* SLIDE 3: Infrastructure */}
          <SlideLayout id="infrastructure" title="Infrastructure & Assets">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 h-full items-stretch">
              <div className="lg:col-span-1 space-y-6">
                <div className="bg-white p-8 rounded-3xl shadow-xl border-b-4 border-[#C9A227] flex flex-col justify-center">
                  <p className="text-slate-500 font-bold uppercase text-xs mb-2">Total Available Land</p>
                  <h4 className="text-5xl font-black text-[#0B5D3B]">507,480</h4>
                  <p className="text-xl font-medium text-slate-600">Sq Ft</p>
                  <div className="mt-6 flex items-center gap-2 text-emerald-600 font-bold text-sm bg-emerald-50 w-fit px-3 py-1 rounded-full">
                    <ArrowUpRight size={16} /> Expanding Soon
                  </div>
                </div>
                <div className="grid grid-cols-1 gap-4">
                  {[
                    { label: 'Sports Ground', icon: <Users />, desc: 'Standard Stadium' },
                    { label: 'Solar Park', icon: <Zap />, desc: '300KW Capacity' },
                    { label: 'Workshops', icon: <Settings />, desc: '12 Advanced Units' }
                  ].map((item, idx) => (
                    <div key={idx} className="bg-white p-4 rounded-2xl shadow-md border border-slate-50 flex items-center gap-4">
                      <div className="p-3 bg-slate-100 rounded-xl text-[#0B5D3B]">
                        {item.icon}
                      </div>
                      <div>
                        <p className="font-bold text-slate-800 leading-none mb-1">{item.label}</p>
                        <p className="text-xs text-slate-500">{item.desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
              <div className="lg:col-span-2 bg-white p-8 rounded-3xl shadow-xl flex flex-col">
                <h3 className="text-xl font-bold text-slate-800 mb-8">Land Allocation Breakdown (Sq Ft)</h3>
                <div className="flex-grow flex items-center">
                  <SimpleBarChart 
                    data={[
                      { name: 'Covered Area', value: 185000 },
                      { name: 'Uncovered Area', value: 322480 },
                      { name: 'Hostel Block', value: 45000 },
                      { name: 'Workshop Area', value: 85000 },
                    ]} 
                    dataKey="value" 
                  />
                </div>
              </div>
            </div>
          </SlideLayout>

          {/* SLIDE 4: Administration */}
          <SlideLayout id="admin" title="Administration & Staffing">
             <div className="relative py-10">
                <div className="flex flex-col items-center gap-12">
                   {/* Principal */}
                   <motion.div initial={{y: 20, opacity: 0}} whileInView={{y: 0, opacity: 1}} className="relative z-10 w-full max-w-sm">
                      <div className="bg-[#0B5D3B] text-white p-6 rounded-3xl shadow-2xl text-center border-b-8 border-[#C9A227]">
                        <h4 className="text-2xl font-bold">Principal</h4>
                        <p className="text-[#C9A227] font-semibold text-sm">GTTI Rahim Yar Khan</p>
                      </div>
                   </motion.div>
                   
                   <div className="w-1 h-12 bg-[#C9A227] hidden md:block" />

                   <div className="grid grid-cols-1 md:grid-cols-3 gap-8 w-full max-w-6xl">
                      {[
                        { role: 'Vice Principal', staff: '1 Position', color: 'bg-emerald-50 border-emerald-200' },
                        { role: 'Chief Instructors', staff: '4 Positions', color: 'bg-blue-50 border-blue-200' },
                        { role: 'Admin Staff', staff: '12 Positions', color: 'bg-purple-50 border-purple-200' }
                      ].map((item, idx) => (
                        <motion.div key={idx} initial={{y: 20, opacity: 0}} whileInView={{y: 0, opacity: 1}} transition={{delay: idx * 0.1}} className={`p-8 rounded-3xl border-2 text-center shadow-lg ${item.color}`}>
                          <h5 className="text-xl font-bold text-slate-800 mb-2">{item.role}</h5>
                          <p className="text-slate-500 font-medium">{item.staff}</p>
                          <div className="mt-4 flex justify-center">
                            <Users className="text-slate-400 opacity-30" size={40} />
                          </div>
                        </motion.div>
                      ))}
                   </div>
                </div>
             </div>
          </SlideLayout>

          {/* SLIDE 5: Industry Linkages */}
          <SlideLayout id="linkages" title="Industry-Academia Linkages">
            <div className="space-y-12">
              <div className="bg-white p-8 rounded-3xl shadow-xl flex flex-col items-center">
                <h3 className="text-xl font-bold mb-10 text-slate-500 uppercase tracking-widest">Our Strategic Partners</h3>
                <div className="flex flex-wrap justify-center gap-16">
                  {['Toyota Royal Motors', 'Fatima Fertilizer', 'Atlas Honda', 'FFC Goth Machi', 'Unilever RYK'].map((name, i) => (
                    <motion.div key={i} whileHover={{scale: 1.1}} className="flex flex-col items-center gap-4">
                      <div className="w-24 h-24 bg-slate-50 rounded-2xl flex items-center justify-center p-4 border border-slate-100 shadow-sm grayscale hover:grayscale-0 transition-all">
                        <img src={`https://picsum.photos/id/${100+i}/100/100`} alt={name} className="object-contain" />
                      </div>
                      <span className="text-xs font-bold text-slate-500 text-center">{name}</span>
                    </motion.div>
                  ))}
                </div>
              </div>

              <div className="bg-slate-50 p-8 rounded-3xl border border-slate-200 relative overflow-hidden">
                <div className="absolute top-0 right-0 w-64 h-64 bg-[#0B5D3B] opacity-5 -mr-32 -mt-32 rounded-full"></div>
                <h3 className="text-xl font-bold mb-8 flex items-center gap-3"><TrendingUp className="text-[#C9A227]" /> Executive Dialogue Timeline</h3>
                <div className="flex flex-col md:flex-row gap-8 relative z-10">
                  {[
                    { date: 'Aug 2025', event: 'MoU with Toyota', icon: <CheckCircle /> },
                    { date: 'Oct 2025', event: 'Industrial Board Meet', icon: <CheckCircle /> },
                    { date: 'Dec 2025', event: 'Recruitment Drive', icon: <CheckCircle /> }
                  ].map((step, i) => (
                    <div key={i} className="flex-1 bg-white p-6 rounded-2xl shadow-sm border-l-4 border-[#0B5D3B]">
                      <p className="text-[#C9A227] font-bold text-sm mb-1">{step.date}</p>
                      <h4 className="font-bold text-slate-800 mb-2">{step.event}</h4>
                      <div className="text-slate-500 text-xs">Successfully negotiated apprenticeship slots for 50+ students.</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </SlideLayout>

          {/* SLIDE 6: Student Development */}
          <SlideLayout id="student-dev" title="Student Development & Placement">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
              <div className="space-y-6">
                <div className="bg-white p-8 rounded-3xl shadow-xl">
                  <h3 className="text-xl font-bold mb-6 text-slate-800">Career Counseling Impact</h3>
                  <div className="h-64">
                    <CustomPieChart 
                      data={[
                        { name: 'Self Employed', value: 35 },
                        { name: 'Industry Placed', value: 45 },
                        { name: 'Further Studies', value: 15 },
                        { name: 'Others', value: 5 },
                      ]}
                      colors={['#0B5D3B', '#C9A227', '#64748b', '#cbd5e1']}
                    />
                  </div>
                </div>
                <ul className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {[
                    '85% Job Placement Rate',
                    '200+ Counseling Sessions',
                    'Bi-annual Job Fairs',
                    'Skill Enhancement Labs'
                  ].map((item, i) => (
                    <li key={i} className="flex items-center gap-3 bg-emerald-50 p-4 rounded-xl border border-emerald-100 font-semibold text-[#0B5D3B]">
                      <CheckCircle size={20} className="text-[#C9A227]" /> {item}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="grid grid-cols-2 gap-4">
                {[1, 2, 3, 4].map(i => (
                  <div key={i} className="relative aspect-square rounded-3xl overflow-hidden shadow-lg group">
                    <img src={`https://picsum.photos/id/${200+i}/400/400`} alt="Activity" className="w-full h-full object-cover transition-transform group-hover:scale-110" />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent flex items-end p-4">
                      <p className="text-white text-xs font-bold">Industrial Visit - {i * 15} Jan 2026</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </SlideLayout>

          {/* SLIDE 7: Events */}
          <SlideLayout id="events" title="Events & Achievements">
            <div className="flex flex-col gap-8 h-full">
              <div className="flex-grow grid grid-cols-1 md:grid-cols-4 gap-6">
                {[
                  { title: 'Appreciation Ceremony', date: 'Sep 2025', icon: <Award className="text-amber-500" /> },
                  { title: 'Student Day', date: 'Nov 2025', icon: <Users className="text-blue-500" /> },
                  { title: 'Speech Contest', date: 'Dec 2025', icon: <FileText className="text-purple-500" /> },
                  { title: 'Annual Sports', date: 'Jan 2026', icon: <Award className="text-emerald-500" /> }
                ].map((item, i) => (
                  <motion.div key={i} whileHover={{scale: 1.05}} className="bg-white p-8 rounded-3xl shadow-xl flex flex-col items-center text-center gap-4">
                    <div className="w-16 h-16 rounded-full bg-slate-50 flex items-center justify-center border border-slate-100 shadow-inner">
                      {item.icon}
                    </div>
                    <div>
                      <h4 className="font-bold text-slate-800">{item.title}</h4>
                      <p className="text-xs text-[#C9A227] font-bold mt-1 uppercase">{item.date}</p>
                    </div>
                  </motion.div>
                ))}
              </div>
              <div className="bg-[#0B5D3B] p-10 rounded-3xl text-white shadow-2xl relative overflow-hidden">
                <div className="absolute -right-20 -bottom-20 w-80 h-80 bg-white/5 rounded-full"></div>
                <h3 className="text-2xl font-bold mb-6 flex items-center gap-3"><Award className="text-[#C9A227]" /> Outstanding Achievements</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 relative z-10">
                  <div className="flex gap-4 items-start">
                    <div className="p-3 bg-white/10 rounded-xl text-[#C9A227]">
                      <CheckCircle size={24} />
                    </div>
                    <div>
                      <h5 className="font-bold text-lg">National Skill Competition</h5>
                      <p className="text-sm opacity-80">GTTI students secured 1st position in CNC machining trade at Provincial level.</p>
                    </div>
                  </div>
                  <div className="flex gap-4 items-start">
                    <div className="p-3 bg-white/10 rounded-xl text-[#C9A227]">
                      <CheckCircle size={24} />
                    </div>
                    <div>
                      <h5 className="font-bold text-lg">Institutional ISO Certification</h5>
                      <p className="text-sm opacity-80">Successfully completed initial audit for Quality Management System standards.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </SlideLayout>

          {/* SLIDE 8: Financial Overview */}
          <SlideLayout id="finance-summary" title="Financial Overview">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {[
                { label: 'Account Code', val: '03', sub: 'Non-Salary Budget', icon: <Settings /> },
                { label: 'Bank Account #', val: '207052', sub: 'HBL Rahim Yar Khan', icon: <Building /> },
                { label: 'Reporting Scope', val: 'Q3', sub: 'FY 2025 - 2026', icon: <TrendingUp /> }
              ].map((card, i) => (
                <div key={i} className="bg-white p-8 rounded-3xl shadow-xl border-l-8 border-[#0B5D3B] hover:shadow-2xl transition-all">
                  <div className="w-12 h-12 bg-slate-50 rounded-xl flex items-center justify-center text-[#C9A227] mb-6">
                    {card.icon}
                  </div>
                  <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">{card.label}</p>
                  <h4 className="text-4xl font-black text-[#0B5D3B] mb-2">{card.val}</h4>
                  <p className="text-slate-500 font-medium">{card.sub}</p>
                </div>
              ))}
            </div>
            <div className="mt-12 bg-emerald-50 p-8 rounded-3xl border border-emerald-100 flex items-center justify-between">
              <div>
                <h4 className="text-xl font-bold text-[#0B5D3B]">Financial Management Integrity</h4>
                <p className="text-slate-600">All expenditures are audited and recorded in the DDO register.</p>
              </div>
              <div className="flex items-center gap-2 bg-[#0B5D3B] text-white px-6 py-3 rounded-2xl font-bold shadow-lg">
                <CheckCircle size={20} /> Audit Clear
              </div>
            </div>
          </SlideLayout>

          {/* SLIDE 9: Budget Status */}
          <SlideLayout id="budget" title="Budget Status 2025-26">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
              <div className="bg-white p-10 rounded-3xl shadow-xl flex flex-col justify-center">
                <p className="text-slate-500 font-bold uppercase text-sm mb-4">Total Funds Available</p>
                <h4 className="text-6xl font-black text-[#0B5D3B] mb-8">
                  <span className="text-2xl align-top mr-2 text-slate-400">PKR</span>
                  12.58M
                </h4>
                <div className="space-y-4">
                  <div className="flex justify-between items-center p-4 bg-slate-50 rounded-2xl">
                    <span className="font-bold text-slate-600">Opening Balance</span>
                    <span className="font-black text-slate-800">4.72M</span>
                  </div>
                  <div className="flex justify-between items-center p-4 bg-slate-50 rounded-2xl">
                    <span className="font-bold text-slate-600">Current Releases</span>
                    <span className="font-black text-slate-800">7.86M</span>
                  </div>
                </div>
              </div>
              <div className="bg-white p-10 rounded-3xl shadow-xl">
                <h3 className="text-xl font-bold mb-8 text-center text-slate-800">Funds Composition (%)</h3>
                <div className="h-80">
                  <CustomPieChart 
                    data={[
                      { name: 'Opening Balance', value: 37.5 },
                      { name: 'Current Releases', value: 62.5 },
                    ]}
                    colors={['#C9A227', '#0B5D3B']}
                  />
                </div>
              </div>
            </div>
          </SlideLayout>

          {/* SLIDE 10: Expenditures */}
          <SlideLayout id="expenses" title="Major Expenditure Heads">
            <div className="bg-white p-10 rounded-3xl shadow-xl h-full flex flex-col">
              <h3 className="text-xl font-bold mb-10 text-slate-800">Non-Salary Expenditure Breakdown (PKR)</h3>
              <div className="flex-grow">
                <SimpleBarChart 
                  data={[
                    { name: 'Training Mats', value: 2450000 },
                    { name: 'Utilities', value: 1200000 },
                    { name: 'Maintenance', value: 850000 },
                    { name: 'Stationery', value: 320000 },
                    { name: 'Misc', value: 180000 },
                  ]} 
                  dataKey="value" 
                />
              </div>
              <div className="mt-8 grid grid-cols-2 md:grid-cols-4 gap-4">
                {[
                  { label: 'Highest', head: 'Training Mats' },
                  { label: 'Utility Growth', head: '+12% YoY' },
                  { label: 'Cost Savings', head: '8% Recycled' },
                  { label: 'Transparency', head: '100% Digital' }
                ].map((stat, i) => (
                  <div key={i} className="p-4 bg-slate-50 rounded-2xl text-center border border-slate-100">
                    <p className="text-[10px] text-slate-400 font-bold uppercase">{stat.label}</p>
                    <p className="font-bold text-[#0B5D3B] truncate">{stat.head}</p>
                  </div>
                ))}
              </div>
            </div>
          </SlideLayout>

          {/* SLIDE 11: Trends */}
          <SlideLayout id="trends" title="Monthly Expense Performance">
            <div className="bg-white p-10 rounded-3xl shadow-xl h-full flex flex-col">
              <div className="flex justify-between items-center mb-10">
                <h3 className="text-xl font-bold text-slate-800">Utilization Trend (July 2025 - Jan 2026)</h3>
                <div className="flex items-center gap-2 bg-emerald-50 text-[#0B5D3B] px-4 py-2 rounded-full font-bold text-sm">
                  <TrendingUp size={16} /> Budget Utilization: 82%
                </div>
              </div>
              <div className="flex-grow">
                <CustomLineChart 
                  data={[
                    { name: 'July', value: 850000 },
                    { name: 'Aug', value: 920000 },
                    { name: 'Sep', value: 1100000 },
                    { name: 'Oct', value: 1050000 },
                    { name: 'Nov', value: 1300000 },
                    { name: 'Dec', value: 1450000 },
                    { name: 'Jan', value: 1200000 },
                  ]}
                  dataKey="value"
                />
              </div>
            </div>
          </SlideLayout>

          {/* SLIDE 12: Reconciliation */}
          <SlideLayout id="reconciliation" title="Closing Balance & Reconciliation">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
              <div className="space-y-8">
                <motion.div 
                  whileHover={{ scale: 1.02 }}
                  className="bg-gradient-to-br from-[#0B5D3B] to-[#04331e] p-10 rounded-3xl text-white shadow-2xl relative overflow-hidden"
                >
                  <div className="absolute top-0 right-0 p-8 opacity-10">
                    <CheckCircle size={120} />
                  </div>
                  <p className="text-[#C9A227] font-black uppercase tracking-widest text-sm mb-4">Current Closing Balance</p>
                  <h3 className="text-6xl font-black mb-6">7,854,778.73</h3>
                  <div className="inline-flex items-center gap-2 bg-white/10 px-4 py-2 rounded-full font-bold text-sm border border-white/20">
                    <CheckCircle size={18} className="text-[#C9A227]" /> 100% Reconciled
                  </div>
                </motion.div>

                <div className="grid grid-cols-2 gap-6">
                   <div className="bg-white p-6 rounded-3xl shadow-lg border border-slate-100">
                     <p className="text-slate-400 text-xs font-bold uppercase mb-2">Reconciliation Status</p>
                     <h5 className="text-xl font-black text-slate-800 uppercase">Verified</h5>
                     <div className="mt-4 h-1 w-12 bg-emerald-500 rounded-full"></div>
                   </div>
                   <div className="bg-white p-6 rounded-3xl shadow-lg border border-slate-100">
                     <p className="text-slate-400 text-xs font-bold uppercase mb-2">Audit Readiness</p>
                     <h5 className="text-xl font-black text-slate-800 uppercase">Level A+</h5>
                     <div className="mt-4 h-1 w-12 bg-blue-500 rounded-full"></div>
                   </div>
                </div>
              </div>

              <div className="bg-white p-10 rounded-3xl shadow-xl">
                 <h4 className="text-xl font-bold mb-8 text-slate-800">Side-by-Side Verification</h4>
                 <div className="space-y-6">
                    <div className="flex items-center gap-6 p-6 bg-slate-50 rounded-2xl border-l-4 border-slate-300">
                       <div className="w-12 h-12 bg-white rounded-xl flex items-center justify-center shadow-sm">
                          <FileText className="text-slate-400" />
                       </div>
                       <div className="flex-grow">
                          <p className="text-xs font-bold text-slate-400 uppercase">Cash Book Balance</p>
                          <p className="text-2xl font-black text-slate-700">7,854,778.73</p>
                       </div>
                    </div>
                    <div className="flex items-center gap-6 p-6 bg-emerald-50 rounded-2xl border-l-4 border-emerald-500">
                       <div className="w-12 h-12 bg-white rounded-xl flex items-center justify-center shadow-sm">
                          <Building className="text-emerald-500" />
                       </div>
                       <div className="flex-grow">
                          <p className="text-xs font-bold text-emerald-600 uppercase">Bank Statement</p>
                          <p className="text-2xl font-black text-emerald-900">7,854,778.73</p>
                       </div>
                    </div>
                    <div className="p-4 bg-emerald-600 rounded-2xl text-white text-center font-bold text-sm shadow-lg">
                       ZERO DISCREPANCY DETECTED
                    </div>
                 </div>
              </div>
            </div>
          </SlideLayout>

          {/* SLIDE 13: Future Expansion */}
          <SlideLayout id="expansion" title="Future Expansion Plans">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {[
                { title: 'IT Trade Revitalization', icon: <TrendingUp />, desc: 'Establishing a state-of-the-art AI and Cloud Computing lab for 100+ students.', color: 'bg-blue-600' },
                { title: 'Solar Technician Course', icon: <Zap />, desc: 'Launching a certified Renewable Energy program to meet local market demands.', color: 'bg-amber-500' },
                { title: 'Advanced Electronics', icon: <Settings />, desc: 'Procuring high-end PLC and robotics kits for industrial automation training.', color: 'bg-emerald-600' }
              ].map((card, i) => (
                <motion.div 
                  key={i}
                  whileHover={{ y: -15 }}
                  className="bg-white p-8 rounded-3xl shadow-xl flex flex-col h-full border-t-8 border-slate-50 relative group"
                >
                  <div className={`absolute -top-6 left-10 w-12 h-12 ${card.color} text-white rounded-2xl flex items-center justify-center shadow-lg transform transition-transform group-hover:scale-110`}>
                    {card.icon}
                  </div>
                  <div className="pt-8 h-full flex flex-col">
                    <h4 className="text-2xl font-black text-slate-800 mb-4">{card.title}</h4>
                    <p className="text-slate-600 leading-relaxed mb-6 flex-grow">{card.desc}</p>
                    <div className="flex items-center gap-2 text-[#C9A227] font-bold text-sm">
                      Learn More <ArrowUpRight size={16} />
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
            <div className="mt-16 flex justify-center">
              <motion.div 
                animate={{ y: [0, -10, 0] }}
                transition={{ repeat: Infinity, duration: 2 }}
                className="flex items-center gap-4 bg-slate-100 px-8 py-4 rounded-full font-bold text-slate-500 shadow-inner"
              >
                <TrendingUp className="text-[#0B5D3B]" /> Continuous Growth Trajectory
              </motion.div>
            </div>
          </SlideLayout>

          {/* SLIDE 14: Challenges */}
          <SlideLayout id="challenges" title="Challenges & Recommendations">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
              <div className="bg-red-50 p-10 rounded-3xl border border-red-100 flex flex-col">
                <h3 className="text-2xl font-bold text-red-700 mb-8 flex items-center gap-3">
                  <AlertTriangle /> Critical Challenges
                </h3>
                <div className="space-y-6 flex-grow">
                  {[
                    { label: 'Inflationary Pressures', desc: 'Sharp increase in material costs affecting practical training budgets.' },
                    { label: 'Infrastructure Age', desc: 'Need for renovation of older hostel blocks and boundary walls.' },
                    { label: 'Staff Shortfall', desc: 'Vacant positions in specialized trades like Electronics and Mechatronics.' }
                  ].map((item, i) => (
                    <div key={i} className="bg-white/60 p-6 rounded-2xl shadow-sm border-l-4 border-red-400">
                      <h4 className="font-bold text-red-900">{item.label}</h4>
                      <p className="text-sm text-red-700 opacity-80 mt-1">{item.desc}</p>
                    </div>
                  ))}
                </div>
              </div>

              <div className="bg-emerald-50 p-10 rounded-3xl border border-emerald-100 flex flex-col">
                <h3 className="text-2xl font-bold text-[#0B5D3B] mb-8 flex items-center gap-3">
                  <CheckCircle /> Recommendations
                </h3>
                <div className="space-y-6 flex-grow">
                  {[
                    { label: 'Clear Un-presented Cheques', desc: 'Immediate action required for 1.6M PKR in outstanding bank transactions.' },
                    { label: 'Strengthen PPPs', desc: 'Further engagement with private sector for subsidized training equipment.' },
                    { label: 'Staff Recruitment', desc: 'Initiate hiring through PPSC/TEVTA for specialized technical roles.' }
                  ].map((item, i) => (
                    <div key={i} className="bg-white/60 p-6 rounded-2xl shadow-sm border-l-4 border-emerald-500">
                      <h4 className="font-bold text-emerald-900">{item.label}</h4>
                      <p className="text-sm text-emerald-700 opacity-80 mt-1">{item.desc}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </SlideLayout>

          {/* SLIDE 15: Conclusion */}
          <SlideLayout id="conclusion" bgImage="https://images.unsplash.com/photo-1541339907198-e08756ebafe3?q=80&w=1600&auto=format&fit=crop">
            <div className="flex flex-col items-center justify-center text-center h-full text-white">
              <motion.div 
                initial={{ opacity: 0, y: 50 }}
                whileInView={{ opacity: 1, y: 0 }}
                className="max-w-4xl"
              >
                <h2 className="text-5xl md:text-7xl font-black mb-12 drop-shadow-lg">Conclusion</h2>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
                  {[
                    { title: 'Administrative Stability', sub: '100% Policy Compliance' },
                    { title: 'Strong Financials', sub: 'No Audit Observations' },
                    { title: 'Improved Quality', sub: 'Top-tier Placement' }
                  ].map((item, i) => (
                    <div key={i} className="bg-white/10 backdrop-blur-lg p-6 rounded-3xl border border-white/20 shadow-xl">
                      <h4 className="font-bold text-lg mb-2">{item.title}</h4>
                      <p className="text-[#C9A227] font-bold text-xs uppercase">{item.sub}</p>
                    </div>
                  ))}
                </div>
                <h3 className="text-4xl font-light mb-8 opacity-90">Thank You for Your Support</h3>
                <div className="w-24 h-1 bg-[#C9A227] mx-auto rounded-full mb-8"></div>
                <p className="text-sm tracking-widest uppercase font-bold opacity-60">
                  GTTI Rahim Yar Khan &bull; Jan 2026
                </p>
              </motion.div>
            </div>
          </SlideLayout>

        </div>
      </div>
    </div>
  );
};

export default App;
